### ISSUE TITLE
Don't compile in prod

### ISSUE THREAD

**Issue by tankejaures** [amitport/ngx-init#1]
Hello thank's 
I want to tell you that it don't work in when we use ng build --prod

If you know how we can resolve it please help me
Now I just remove it and it work fine in production

Thank's for your help

**Comment by amitport** [comment]
Hi, can you attach the output of `ng version` from your project's folder?

**Comment by tankejaures** [comment]
Angular CLI: 8.1.3
Node: 10.15.2
OS: win32 x64
Angular: 8.1.3
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.35.2

**Comment by amitport** [comment]
following https://github.com/angular/angular-cli/issues/12290
in `angular-cli@8` libraries are always build in production :)

updated master to v8
